### PR TITLE
tr.json

### PR DESCRIPTION
**Pull request by zenychan**

### CODE REVIEW

**Review by Floogen — APPROVED** [review]

**Comment by Floogen** [comment]
Hello there!

Thank for for providing the Turkish translation. I've approved and merged your tr.json! 

How would you like to be credited on the main page? Currently it'll appear as so:
**Turkish - zenychan**

**Comment by zenychan** [comment]
You are welcome! I really enjoy translating mods and it was a great pleasure to translate this mod as well.
And yes, zenychan is alright. I use the same name on nexus, too.

**Comment by zenychan** [comment]
uuuh i just realized bailing bucket's empty description and full description are reversed so you might want to edit the files.

**Comment by Floogen** [comment]
Good catch! I just flipped them for the default and the two translated JSON files.

**Comment by Floogen** [comment]
I've released v1.2.2 with the Turkish translation!
image

**Pull request merged**
