### PR TITLE
korean Translation(have issue)

### PR DESCRIPTION
**Pull request by Kayayak**
1. not have Murphy name key(when speak with him, under of his portrait)
2. day of the week in "game_message.readable_note" always show english :
ex) "쪽지가 있다...#머피의 쪽지다! 매주 Friday마다 정박할거고, 낚시 여행을 가고 싶다면 해가 지기 전에 찾아와서 말해달라고 써있다.",
3.Speach bubble( Status messages during trawler trip) not apply translated in game
4.no have translation key for UI

### CODE REVIEW

**Comment by Floogen** [comment]
Per the commit, I've fixed the issue with the speech bubbles not appearing despite being translated. I've also added the translation UI keys and Murphy's name to the default.json.

For the English day of the week, I have done a temporary fix of it just saying Murphy will appear next week instead of specifics. I'll have to look into how the game handles it.

**Comment by Kayayak** [comment]
Update translation! I don't know coding so not ingame tested in this build XD

**Comment by Floogen** [comment]
I've merged the changes over to development in preparations for a new release.

Did you have a preference in how you'd like to be credited for the translations? Currently it will appear as so on the Nexus page:
**Korean translation provided by - Kayayak**

**Comment by Kayayak** [comment]
Can you write as KAYA? my mod page is here!  https://www.nexusmods.com/users/48693548 :D

**Comment by Floogen** [comment]
I've released v1.2.1 and credited your name as requested! Thank you for all your work!

image

**Pull request merged**
